"""Run this once to seed 30 lawyer profiles into the database."""
import asyncio
import json
import sys
import os

sys.path.insert(0, os.path.dirname(__file__))

from app.core.database import async_session, create_tables
from app.models.lawyer import Lawyer

LAWYERS = [
    # Delhi
    {
        "full_name": "Adv. Rajeev Sharma",
        "bar_council_number": "D/1234/2005",
        "specializations": ["Criminal Defense", "Bail & Anticipatory Bail"],
        "practice_areas": ["Criminal Law", "NDPS Act", "IPC Offences", "Cyber Crimes"],
        "city": "Delhi",
        "state": "Delhi",
        "years_experience": 19,
        "hourly_rate": 5000,
        "consultation_fee": 2000,
        "rating": 4.8,
        "review_count": 312,
        "languages": ["Hindi", "English", "Punjabi"],
        "bio": "Senior advocate at Delhi High Court with 19 years of experience in criminal defense. Successfully handled 500+ bail matters and complex criminal trials. Former public prosecutor turned defense attorney.",
        "court_levels": ["District Court", "High Court", "Supreme Court"],
        "available": True,
        "verified": True,
    },
    {
        "full_name": "Adv. Priya Menon",
        "bar_council_number": "D/2890/2010",
        "specializations": ["Corporate Law", "Mergers & Acquisitions", "SEBI Compliance"],
        "practice_areas": ["Corporate Law", "Securities Law", "Contract Law", "Start-up Advisory"],
        "city": "Delhi",
        "state": "Delhi",
        "years_experience": 14,
        "hourly_rate": 8000,
        "consultation_fee": 3000,
        "rating": 4.9,
        "review_count": 198,
        "languages": ["English", "Hindi", "Malayalam"],
        "bio": "Corporate lawyer specializing in M&A, PE/VC investments, and SEBI regulations. Advised 50+ startups on fundraising and regulatory compliance. Former associate at a top-tier law firm.",
        "court_levels": ["Tribunal", "High Court"],
        "available": True,
        "verified": True,
    },
    {
        "full_name": "Adv. Vikram Singh Chauhan",
        "bar_council_number": "D/445/1998",
        "specializations": ["Constitutional Law", "PIL", "Fundamental Rights"],
        "practice_areas": ["Constitutional Law", "Administrative Law", "Writ Jurisdiction", "Human Rights"],
        "city": "Delhi",
        "state": "Delhi",
        "years_experience": 26,
        "hourly_rate": 12000,
        "consultation_fee": 5000,
        "rating": 4.7,
        "review_count": 445,
        "languages": ["Hindi", "English"],
        "bio": "Leading constitutional lawyer with 26 years at Supreme Court. Filed landmark PILs on environment, education, and transparency. Former Standing Counsel for a State Government.",
        "court_levels": ["High Court", "Supreme Court"],
        "available": True,
        "verified": True,
    },
    {
        "full_name": "Adv. Neha Agarwal",
        "bar_council_number": "D/3102/2012",
        "specializations": ["Family Law", "Divorce & Custody", "Domestic Violence"],
        "practice_areas": ["Family Law", "Matrimonial Disputes", "Child Custody", "Maintenance"],
        "city": "Delhi",
        "state": "Delhi",
        "years_experience": 12,
        "hourly_rate": 4000,
        "consultation_fee": 1500,
        "rating": 4.6,
        "review_count": 267,
        "languages": ["Hindi", "English"],
        "bio": "Compassionate family lawyer with deep expertise in matrimonial disputes, child custody, and domestic violence cases. Volunteer legal aid provider at women's shelters.",
        "court_levels": ["Family Court", "District Court", "High Court"],
        "available": True,
        "verified": True,
    },
    {
        "full_name": "Adv. Sanjay Khanna",
        "bar_council_number": "D/892/2003",
        "specializations": ["Property Law", "Real Estate", "RERA"],
        "practice_areas": ["Property Law", "Real Estate", "RERA Disputes", "Landlord-Tenant"],
        "city": "Delhi",
        "state": "Delhi",
        "years_experience": 21,
        "hourly_rate": 6000,
        "consultation_fee": 2500,
        "rating": 4.5,
        "review_count": 334,
        "languages": ["Hindi", "English", "Punjabi"],
        "bio": "Expert in property disputes, RERA complaints against builders, and real estate transactions. Handled 200+ RERA cases and recovered ₹150+ crore for homebuyers.",
        "court_levels": ["RERA Authority", "District Court", "High Court"],
        "available": True,
        "verified": True,
    },
    # Mumbai
    {
        "full_name": "Adv. Aishwarya Desai",
        "bar_council_number": "MH/5621/2008",
        "specializations": ["Insolvency & Bankruptcy", "IBC", "NCLT"],
        "practice_areas": ["Insolvency Law", "Corporate Restructuring", "Banking & Finance", "NPA Recovery"],
        "city": "Mumbai",
        "state": "Maharashtra",
        "years_experience": 16,
        "hourly_rate": 10000,
        "consultation_fee": 4000,
        "rating": 4.9,
        "review_count": 156,
        "languages": ["English", "Hindi", "Marathi"],
        "bio": "Leading IBC practitioner before NCLT Mumbai and NCLAT. Handled 100+ corporate insolvency resolution processes with assets exceeding ₹5,000 crore. Former CA and bankruptcy trustee.",
        "court_levels": ["NCLT", "NCLAT", "Supreme Court"],
        "available": True,
        "verified": True,
    },
    {
        "full_name": "Adv. Rohit Parekh",
        "bar_council_number": "MH/3201/2006",
        "specializations": ["Cheque Bounce", "NI Act 138", "Debt Recovery"],
        "practice_areas": ["Cheque Bounce Cases", "Debt Recovery", "DRT Matters", "Commercial Disputes"],
        "city": "Mumbai",
        "state": "Maharashtra",
        "years_experience": 18,
        "hourly_rate": 5500,
        "consultation_fee": 2000,
        "rating": 4.7,
        "review_count": 521,
        "languages": ["Hindi", "English", "Gujarati", "Marathi"],
        "bio": "Specialist in NI Act Section 138 cheque bounce cases with 1500+ successful cases. Quick recovery specialist using legal notices and fast-track court procedures.",
        "court_levels": ["Magistrate Court", "Sessions Court", "High Court"],
        "available": True,
        "verified": True,
    },
    {
        "full_name": "Adv. Meera Nair",
        "bar_council_number": "MH/7823/2014",
        "specializations": ["Consumer Protection", "RERA", "E-Commerce Disputes"],
        "practice_areas": ["Consumer Law", "RERA", "Product Liability", "E-Commerce"],
        "city": "Mumbai",
        "state": "Maharashtra",
        "years_experience": 10,
        "hourly_rate": 4500,
        "consultation_fee": 1500,
        "rating": 4.8,
        "review_count": 289,
        "languages": ["English", "Hindi", "Malayalam", "Marathi"],
        "bio": "Consumer rights activist-lawyer with 10 years fighting for buyers against builders, e-commerce companies, and service deficiencies. 95% success rate in consumer forum cases.",
        "court_levels": ["Consumer Forum", "RERA Authority", "High Court"],
        "available": True,
        "verified": True,
    },
    {
        "full_name": "Adv. Cyrus Irani",
        "bar_council_number": "MH/1102/2001",
        "specializations": ["Intellectual Property", "Trademark", "Patent"],
        "practice_areas": ["IP Law", "Trademark Registration", "Patent Filing", "Copyright", "Trade Secrets"],
        "city": "Mumbai",
        "state": "Maharashtra",
        "years_experience": 23,
        "hourly_rate": 9000,
        "consultation_fee": 3500,
        "rating": 4.6,
        "review_count": 203,
        "languages": ["English", "Hindi", "Gujarati"],
        "bio": "IP specialist with Bombay High Court practice. Registered 500+ trademarks and 50+ patents. Advisor to Bollywood studios, tech companies, and pharma firms on IP strategy.",
        "court_levels": ["IP Office", "High Court", "Supreme Court"],
        "available": True,
        "verified": True,
    },
    {
        "full_name": "Adv. Sunita Joshi",
        "bar_council_number": "MH/4512/2009",
        "specializations": ["Labour Law", "Employment Disputes", "POSH"],
        "practice_areas": ["Labour Law", "Industrial Disputes", "POSH Compliance", "Employment Contracts"],
        "city": "Mumbai",
        "state": "Maharashtra",
        "years_experience": 15,
        "hourly_rate": 6000,
        "consultation_fee": 2500,
        "rating": 4.5,
        "review_count": 178,
        "languages": ["Hindi", "English", "Marathi"],
        "bio": "Labour and employment specialist representing both employees and employers. POSH compliance trainer for 50+ companies. Expert in wrongful termination and retrenchment disputes.",
        "court_levels": ["Labour Court", "Industrial Tribunal", "High Court"],
        "available": True,
        "verified": True,
    },
    # Bangalore
    {
        "full_name": "Adv. Karthik Rao",
        "bar_council_number": "KA/3421/2011",
        "specializations": ["Tech & Startup Law", "Data Privacy", "IT Act"],
        "practice_areas": ["Technology Law", "Start-up Advisory", "Data Privacy", "Cyber Law", "IT Contracts"],
        "city": "Bangalore",
        "state": "Karnataka",
        "years_experience": 13,
        "hourly_rate": 7500,
        "consultation_fee": 3000,
        "rating": 4.9,
        "review_count": 231,
        "languages": ["English", "Hindi", "Kannada", "Tamil"],
        "bio": "Go-to tech lawyer for Bangalore startups. DPDPA compliance specialist, IT Act litigation expert, and SaaS contract drafter. Former legal counsel at a unicorn startup.",
        "court_levels": ["Cyber Crime Court", "High Court", "Tribunal"],
        "available": True,
        "verified": True,
    },
    {
        "full_name": "Adv. Divya Krishnamurthy",
        "bar_council_number": "KA/1987/2007",
        "specializations": ["Matrimonial Law", "NRI Divorce", "Child Custody"],
        "practice_areas": ["Family Law", "NRI Matrimonial", "International Child Custody", "Maintenance"],
        "city": "Bangalore",
        "state": "Karnataka",
        "years_experience": 17,
        "hourly_rate": 5000,
        "consultation_fee": 2000,
        "rating": 4.7,
        "review_count": 312,
        "languages": ["English", "Kannada", "Tamil", "Hindi"],
        "bio": "Specialist in NRI matrimonial cases and cross-border child custody disputes. Appeared before Karnataka HC and coordinated with international lawyers in USA, UK, and UAE.",
        "court_levels": ["Family Court", "District Court", "High Court"],
        "available": True,
        "verified": True,
    },
    {
        "full_name": "Adv. Ramesh Hegde",
        "bar_council_number": "KA/789/2000",
        "specializations": ["Criminal Law", "Organized Crime", "White Collar Crime"],
        "practice_areas": ["Criminal Law", "White Collar Crime", "Economic Offences", "Enforcement Directorate"],
        "city": "Bangalore",
        "state": "Karnataka",
        "years_experience": 24,
        "hourly_rate": 10000,
        "consultation_fee": 4000,
        "rating": 4.6,
        "review_count": 189,
        "languages": ["Kannada", "English", "Hindi"],
        "bio": "Senior criminal defense lawyer specializing in ED/CBI/IT department cases. Handled high-profile economic offence cases before Karnataka HC and Supreme Court.",
        "court_levels": ["Sessions Court", "High Court", "Supreme Court"],
        "available": True,
        "verified": True,
    },
    {
        "full_name": "Adv. Shruti Pai",
        "bar_council_number": "KA/5612/2015",
        "specializations": ["Real Estate", "RERA Karnataka", "Property Registration"],
        "practice_areas": ["Property Law", "RERA", "Real Estate Transactions", "Encumbrance Verification"],
        "city": "Bangalore",
        "state": "Karnataka",
        "years_experience": 9,
        "hourly_rate": 4000,
        "consultation_fee": 1500,
        "rating": 4.8,
        "review_count": 267,
        "languages": ["Kannada", "English", "Hindi", "Tulu"],
        "bio": "RERA specialist for Karnataka with deep knowledge of Bangalore real estate laws. Helps IT professionals navigate property purchases, documentation, and builder disputes.",
        "court_levels": ["RERA Authority", "City Civil Court", "High Court"],
        "available": True,
        "verified": True,
    },
    # Chennai
    {
        "full_name": "Adv. Vijayalakshmi Sundaram",
        "bar_council_number": "TN/2341/2004",
        "specializations": ["Arbitration", "Commercial Disputes", "Contract Law"],
        "practice_areas": ["Arbitration", "Mediation", "Commercial Law", "Construction Disputes", "International Arbitration"],
        "city": "Chennai",
        "state": "Tamil Nadu",
        "years_experience": 20,
        "hourly_rate": 8000,
        "consultation_fee": 3000,
        "rating": 4.8,
        "review_count": 143,
        "languages": ["Tamil", "English", "Hindi"],
        "bio": "Accredited arbitrator (ICADR) with 20 years of experience in domestic and international commercial arbitration. Regular arbitrator in construction, infrastructure, and IT disputes.",
        "court_levels": ["Arbitral Tribunal", "High Court", "Supreme Court"],
        "available": True,
        "verified": True,
    },
    {
        "full_name": "Adv. Murugan Pillai",
        "bar_council_number": "TN/891/1997",
        "specializations": ["Constitutional Law", "Service Matters", "Administrative Law"],
        "practice_areas": ["Service Law", "Government Employment Disputes", "Administrative Law", "Writ Petitions"],
        "city": "Chennai",
        "state": "Tamil Nadu",
        "years_experience": 27,
        "hourly_rate": 7000,
        "consultation_fee": 2500,
        "rating": 4.7,
        "review_count": 389,
        "languages": ["Tamil", "English"],
        "bio": "Expert in government service disputes with 27 years at Madras High Court. Represented government employees across Tamil Nadu in service, promotion, and pension disputes.",
        "court_levels": ["CAT", "High Court", "Supreme Court"],
        "available": True,
        "verified": True,
    },
    {
        "full_name": "Adv. Kavitha Rajan",
        "bar_council_number": "TN/4123/2013",
        "specializations": ["Consumer Rights", "Banking Law", "Insurance Disputes"],
        "practice_areas": ["Consumer Law", "Banking Disputes", "Insurance Claims", "Credit Card Fraud"],
        "city": "Chennai",
        "state": "Tamil Nadu",
        "years_experience": 11,
        "hourly_rate": 3500,
        "consultation_fee": 1200,
        "rating": 4.6,
        "review_count": 445,
        "languages": ["Tamil", "English", "Telugu"],
        "bio": "Consumer rights champion with specialization in banking frauds, insurance claim rejections, and online fraud recovery. Helped 300+ clients recover money from banks and insurers.",
        "court_levels": ["Consumer Forum", "Banking Ombudsman", "High Court"],
        "available": True,
        "verified": True,
    },
    # Hyderabad
    {
        "full_name": "Adv. Rajesh Reddy",
        "bar_council_number": "TS/2134/2009",
        "specializations": ["Corporate Law", "Land Acquisition", "Government Contracts"],
        "practice_areas": ["Corporate Law", "Land Acquisition", "Infrastructure Projects", "Public Procurement"],
        "city": "Hyderabad",
        "state": "Telangana",
        "years_experience": 15,
        "hourly_rate": 7000,
        "consultation_fee": 2500,
        "rating": 4.7,
        "review_count": 198,
        "languages": ["Telugu", "Hindi", "English", "Urdu"],
        "bio": "Corporate and government contract specialist with expertise in land acquisition disputes for infrastructure projects in Andhra Pradesh and Telangana.",
        "court_levels": ["High Court", "NCLAT", "Supreme Court"],
        "available": True,
        "verified": True,
    },
    {
        "full_name": "Adv. Faisal Ahmed",
        "bar_council_number": "TS/1102/2006",
        "specializations": ["Property Law", "Wakf Matters", "Muslim Personal Law"],
        "practice_areas": ["Property Law", "Muslim Personal Law", "Wakf Board Disputes", "Family Partition"],
        "city": "Hyderabad",
        "state": "Telangana",
        "years_experience": 18,
        "hourly_rate": 5000,
        "consultation_fee": 2000,
        "rating": 4.5,
        "review_count": 276,
        "languages": ["Urdu", "Hindi", "Telugu", "English"],
        "bio": "Expert in Muslim personal law, Wakf property disputes, and family partition matters in Hyderabad. Practiced at Telangana HC for 18 years.",
        "court_levels": ["Wakf Tribunal", "District Court", "High Court"],
        "available": True,
        "verified": True,
    },
    {
        "full_name": "Adv. Swathi Nambiar",
        "bar_council_number": "TS/3891/2016",
        "specializations": ["Labour Law", "ESIC", "PF Disputes"],
        "practice_areas": ["Labour Law", "PF Disputes", "ESIC Matters", "Workmen Compensation"],
        "city": "Hyderabad",
        "state": "Telangana",
        "years_experience": 8,
        "hourly_rate": 3500,
        "consultation_fee": 1200,
        "rating": 4.8,
        "review_count": 167,
        "languages": ["Telugu", "English", "Hindi", "Malayalam"],
        "bio": "Young and dynamic labour lawyer with specialization in PF/ESIC disputes and workmen compensation cases. Digital-first approach with online consultations available.",
        "court_levels": ["Labour Court", "ESIC Court", "High Court"],
        "available": True,
        "verified": True,
    },
    # Pune
    {
        "full_name": "Adv. Abhijit Deshmukh",
        "bar_council_number": "MH/8921/2007",
        "specializations": ["Criminal Law", "POCSO", "Cyber Crimes"],
        "practice_areas": ["Criminal Law", "POCSO Cases", "Cyber Crimes", "Special Courts"],
        "city": "Pune",
        "state": "Maharashtra",
        "years_experience": 17,
        "hourly_rate": 5500,
        "consultation_fee": 2000,
        "rating": 4.6,
        "review_count": 234,
        "languages": ["Marathi", "Hindi", "English"],
        "bio": "Criminal defense specialist with expertise in POCSO cases and cyber crimes. Appointed amicus curiae by Bombay HC in multiple child protection cases.",
        "court_levels": ["Sessions Court", "Special Court", "High Court"],
        "available": True,
        "verified": True,
    },
    {
        "full_name": "Adv. Rashmi Kulkarni",
        "bar_council_number": "MH/6234/2012",
        "specializations": ["GST", "Direct Tax", "Income Tax Appeals"],
        "practice_areas": ["Tax Law", "GST Disputes", "Income Tax", "Customs Law", "Transfer Pricing"],
        "city": "Pune",
        "state": "Maharashtra",
        "years_experience": 12,
        "hourly_rate": 6500,
        "consultation_fee": 2500,
        "rating": 4.9,
        "review_count": 312,
        "languages": ["Marathi", "Hindi", "English"],
        "bio": "Tax attorney and former IRS officer with expertise in GST, income tax appeals, and transfer pricing disputes. Represented clients before ITAT, High Court, and GST Appellate Authority.",
        "court_levels": ["ITAT", "GST Appellate", "High Court"],
        "available": True,
        "verified": True,
    },
    # Kolkata
    {
        "full_name": "Adv. Subhash Chakraborty",
        "bar_council_number": "WB/1234/2002",
        "specializations": ["Constitutional Law", "Public Interest Litigation"],
        "practice_areas": ["Constitutional Law", "PIL", "Environmental Law", "Human Rights"],
        "city": "Kolkata",
        "state": "West Bengal",
        "years_experience": 22,
        "hourly_rate": 6000,
        "consultation_fee": 2000,
        "rating": 4.7,
        "review_count": 289,
        "languages": ["Bengali", "Hindi", "English"],
        "bio": "Senior advocate at Calcutta High Court with 22 years in constitutional law and PIL. Filed landmark environmental PILs on Ganga pollution and industrial waste disposal in West Bengal.",
        "court_levels": ["High Court", "NGT", "Supreme Court"],
        "available": True,
        "verified": True,
    },
    {
        "full_name": "Adv. Sunanda Roy",
        "bar_council_number": "WB/3421/2010",
        "specializations": ["Family Law", "Dowry Cases", "Women's Rights"],
        "practice_areas": ["Family Law", "Dowry/498A Cases", "Domestic Violence", "Women Rights"],
        "city": "Kolkata",
        "state": "West Bengal",
        "years_experience": 14,
        "hourly_rate": 4000,
        "consultation_fee": 1500,
        "rating": 4.8,
        "review_count": 356,
        "languages": ["Bengali", "Hindi", "English"],
        "bio": "Women's rights advocate specializing in dowry cases, domestic violence, and matrimonial disputes. Legal aid provider for underprivileged women. Associated with women's rights NGOs.",
        "court_levels": ["Family Court", "District Court", "High Court"],
        "available": True,
        "verified": True,
    },
    {
        "full_name": "Adv. Arijit Bose",
        "bar_council_number": "WB/892/1999",
        "specializations": ["Commercial Law", "Shipping & Maritime", "International Trade"],
        "practice_areas": ["Maritime Law", "Admiralty", "Shipping Disputes", "International Trade", "Customs"],
        "city": "Kolkata",
        "state": "West Bengal",
        "years_experience": 25,
        "hourly_rate": 9000,
        "consultation_fee": 3500,
        "rating": 4.6,
        "review_count": 134,
        "languages": ["Bengali", "English", "Hindi"],
        "bio": "One of India's leading maritime lawyers with 25 years in shipping, admiralty, and international trade disputes. Regular arbitrator in ICC and LCIA maritime arbitrations.",
        "court_levels": ["High Court Admiralty", "Supreme Court", "Arbitral Tribunal"],
        "available": True,
        "verified": True,
    },
    # Ahmedabad
    {
        "full_name": "Adv. Paresh Shah",
        "bar_council_number": "GJ/2341/2005",
        "specializations": ["Business Law", "Partnership Disputes", "Commercial Litigation"],
        "practice_areas": ["Business Law", "Partnership Disputes", "Commercial Litigation", "Company Law"],
        "city": "Ahmedabad",
        "state": "Gujarat",
        "years_experience": 19,
        "hourly_rate": 6000,
        "consultation_fee": 2500,
        "rating": 4.7,
        "review_count": 278,
        "languages": ["Gujarati", "Hindi", "English"],
        "bio": "Expert in business and commercial disputes in Gujarat. Handled 100+ partnership dissolution cases and company disputes before Gujarat HC and NCLT Ahmedabad.",
        "court_levels": ["District Court", "High Court", "NCLT"],
        "available": True,
        "verified": True,
    },
    {
        "full_name": "Adv. Manjula Patel",
        "bar_council_number": "GJ/1102/2008",
        "specializations": ["Property Law", "Agriculture Land", "Revenue Matters"],
        "practice_areas": ["Property Law", "Agriculture Land Disputes", "Revenue Court Matters", "Tenancy Law"],
        "city": "Ahmedabad",
        "state": "Gujarat",
        "years_experience": 16,
        "hourly_rate": 4500,
        "consultation_fee": 1800,
        "rating": 4.5,
        "review_count": 345,
        "languages": ["Gujarati", "Hindi", "English"],
        "bio": "Expert in Gujarat's unique land revenue laws and agricultural land disputes. Handled tenancy, non-agricultural permission (NA), and ceiling act matters across Gujarat.",
        "court_levels": ["Revenue Court", "District Court", "High Court"],
        "available": True,
        "verified": True,
    },
    {
        "full_name": "Adv. Devang Mehta",
        "bar_council_number": "GJ/4512/2015",
        "specializations": ["Cheque Bounce", "Recovery", "Winding Up"],
        "practice_areas": ["Cheque Bounce", "Debt Recovery", "Winding Up Petition", "DRT Matters"],
        "city": "Ahmedabad",
        "state": "Gujarat",
        "years_experience": 9,
        "hourly_rate": 3500,
        "consultation_fee": 1200,
        "rating": 4.8,
        "review_count": 423,
        "languages": ["Gujarati", "Hindi", "English"],
        "bio": "Prolific cheque bounce lawyer with 800+ Section 138 cases. Young and tech-savvy with a dedicated online case tracking system for clients.",
        "court_levels": ["Magistrate Court", "Sessions Court", "High Court"],
        "available": True,
        "verified": True,
    },
    {
        "full_name": "Adv. Nandita Kapoor",
        "bar_council_number": "GJ/3102/2011",
        "specializations": ["Tax Law", "VAT", "GST", "Custom Duty"],
        "practice_areas": ["Indirect Tax", "GST", "Customs", "Anti-Dumping", "FEMA"],
        "city": "Ahmedabad",
        "state": "Gujarat",
        "years_experience": 13,
        "hourly_rate": 7000,
        "consultation_fee": 2500,
        "rating": 4.6,
        "review_count": 189,
        "languages": ["Gujarati", "Hindi", "English"],
        "bio": "Indirect tax specialist serving Gujarat's textile and chemical industry. GST refund specialist with 95% success rate. Former Additional Commissioner Customs turned lawyer.",
        "court_levels": ["GST Appellate", "Customs Excise Tribunal", "High Court"],
        "available": True,
        "verified": True,
    },
    {
        "full_name": "Adv. Ishaan Trivedi",
        "bar_council_number": "GJ/5891/2017",
        "specializations": ["RTI", "Consumer Rights", "Anti-Corruption"],
        "practice_areas": ["RTI Matters", "Consumer Law", "Anti-Corruption", "Vigilance"],
        "city": "Ahmedabad",
        "state": "Gujarat",
        "years_experience": 7,
        "hourly_rate": 2500,
        "consultation_fee": 1000,
        "rating": 4.9,
        "review_count": 534,
        "languages": ["Gujarati", "Hindi", "English"],
        "bio": "Young RTI activist-lawyer who has filed 1000+ RTIs exposing corruption. Affordable legal services for middle-class citizens. RTI trainer and public advocate.",
        "court_levels": ["Information Commission", "Consumer Forum", "District Court"],
        "available": True,
        "verified": True,
    },
]


async def seed():
    await create_tables()

    async with async_session() as session:
        for data in LAWYERS:
            lawyer = Lawyer(
                full_name=data["full_name"],
                bar_council_number=data["bar_council_number"],
                specializations=json.dumps(data["specializations"]),
                practice_areas=json.dumps(data["practice_areas"]),
                city=data["city"],
                state=data["state"],
                years_experience=data["years_experience"],
                hourly_rate=data["hourly_rate"],
                consultation_fee=data["consultation_fee"],
                rating=data["rating"],
                review_count=data["review_count"],
                languages=json.dumps(data["languages"]),
                bio=data["bio"],
                court_levels=json.dumps(data["court_levels"]),
                available=data["available"],
                verified=data["verified"],
            )
            session.add(lawyer)
        await session.commit()
        print(f"Seeded {len(LAWYERS)} lawyers successfully.")


if __name__ == "__main__":
    asyncio.run(seed())
